name: basic-mail
services:
  app:
    build: .
    env_file:
      - .env
    expose:
      - ${PORT}
    restart: unless-stopped
    networks:
      - default
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 80
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - default
networks:
  default: